config/routes.rb
Rails.application.routes.draw do
  resources :fruits
  resources :posts
  ##
  # Workaround a "bug" in lighthouse CLI
  #
  # Lighthouse CLI (versions 5.4 - 5.6 tested) issues a `GET /asset-manifest.json`
  # request during its run - the URL seems to be hard-coded. This file does not
  # exist so, during tests, your test will fail because rails will die with a 404.
  #
  # Lighthouse run from Chrome Dev-tools does not have the same behaviour.
  #
  # This hack works around this. This behaviour might be fixed by the time you
  # read this. You can check by commenting out this block and running the
  # accessibility and performance tests. You are encouraged to remove this hack
  # as soon as it is no longer needed.
  #
  if defined?(Webpacker) && Rails.env.test?
    # manifest paths depend on your webpacker config so we inspect it
    manifest_path = Webpacker::Configuration
                    .new(root_path: Rails.root, config_path: Rails.root.join("config/webpacker.yml"), env: Rails.env)
                    .public_manifest_path
                    .relative_path_from(Rails.root.join("public"))
                    .to_s
    get "/asset-manifest.json", to: redirect(manifest_path)
  end

  root "home#index"
  mount OkComputer::Engine, at: "/healthchecks"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: %i[show edit update destroy]

  # GET /fruits
  def index
    @fruits = Fruit.all
  end

  # GET /fruits/1
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits
  def create
    @fruit = Fruit.new(fruit_params)

    if @fruit.save
      redirect_to @fruit, notice: "Fruit was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /fruits/1
  def update
    if @fruit.update(fruit_params)
      redirect_to @fruit, notice: "Fruit was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /fruits/1
  def destroy
    @fruit.destroy
    redirect_to fruits_url, notice: "Fruit was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_fruit
    @fruit = Fruit.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def fruit_params
    params.require(:fruit).permit(:name, :colour, :taste)
  end
end

app/controllers/home_controller.rb
# Renders the home page.
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:name, :title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/retina_image_helper.rb
module RetinaImageHelper
  # Like the Rails image_tag, but adds a srcset attribute with an @2x version
  # of the image, thereby ensuring the image looks great on retina devices.
  # Assumes that the retina version of the image is named the same with "@2x"
  # before the extension, like "image@2x.png". For example:
  #
  #   <%= retina_image_tag("logo.png") %>
  #
  # Produces:
  #
  #   <img src="/assets/logo.png"
  #        srcset="/assets/logo.png 1x,/assets/logo@2x.png 2x">
  #
  # The srcset attribute is supported by modern desktop browsers and iOS 8+.
  def retina_image_tag(src, options={})
    src_1x = image_path(src)
    src_2x = image_path(src.sub(/^(.*)(\.[^.]+)$/, '\1@2x\2'))
    srcset = "#{src_1x} 1x,#{src_2x} 2x"

    tag(:img, options.reverse_merge(src: src_1x, srcset: srcset, alt: ""))
  end
end

app/views/application/_breadcrumb.html.erb
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><a href="#">Home</a></li>
    <li><a href="#">Features</a></li>
    <li class="disabled">Another level</li>
    <li>
      <span class="show-for-sr">Current: </span>Real home page
    </li>
  </ul>
</nav>

app/views/application/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/application/_footer.html.erb
<footer class="footer">
  <p>Footer</p>
</footer>

app/views/application/_pagination.html.erb
<nav aria-label="Pagination">
  <ul class="pagination">
    <li class="pagination-previous disabled">Previous <span class="show-for-sr">page</span></li>
    <li class="current"><span class="show-for-sr">You're on page</span> 1</li>
    <li><a href="#" aria-label="Page 2">2</a></li>
    <li><a href="#" aria-label="Page 3">3</a></li>
    <li><a href="#" aria-label="Page 4">4</a></li>
    <li class="ellipsis" aria-hidden="true"></li>
    <li><a href="#" aria-label="Page 12">12</a></li>
    <li><a href="#" aria-label="Page 13">13</a></li>
    <li class="pagination-next"><a href="#" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
  </ul>
</nav>

app/views/application/header/_header.html.erb
<header class="header">
  <div class="header__bar">
    <div class="header__bar--left">
      <span class="header__bar-title">Site title</span>
    </div>
    <div class="header__bar--right">
      <button class="navigation__button navigation__button--toggle" type="button" data-toggle="main-menu" aria-label="Open menu"></button>
    </div>
  </div>
  <%= render "application/header/navigation" %>
</header>

app/views/application/header/_navigation.html.erb
<section class="navigation__wrapper" id="main-menu" data-toggler=".navigation__wrapper--open">
  <nav class="navigation" role="menu">
    <ul class="navigation__list">
      <li class="navigation__item"><a href="/"><%= image_pack_tag "logo.svg", alt: "Ackama" %></a></li>
    </ul>
    <ul class="navigation__list navigation__list--right" data-accordion-menu data-slide-speed="0" data-multi-open="false">
      <li class="navigation__item"><a href="#">Right item 1</a></li>
      <li class="navigation__item"><a href="#">Right item 2</a></li>
      <li class="navigation__item">
        <a href="#">Right item 3</a>
        <ul class="navigation__list">
          <li><a href="#">Right item 1aaaaaaaaaaaaaaaaaaaaaaa</a></li>
          <li><a href="#">Right item 1b</a></li>
          <li><a href="#">Right item 1c</a></li>
        </ul>
      </li>
      <li class="navigation__item navigation__item--search">
        <%= render "application/header/search" %>
      </li>
    </ul>
  </nav>
  <nav class="navigation" role="menu">
    <ul class="navigation__list" data-accordion-menu data-slide-speed="0" data-multi-open="false">
      <li class="navigation__item navigation__item--borderless">
        <a href="/">Left item 1</a>
        <ul class="navigation__list">
          <li><a href="#">Left item 1aaaaaaaaaaaaaaaaaaaaaaa</a></li>
          <li><a href="#">Left item 1b</a></li>
          <li><a href="#">Left item 1c</a></li>
        </ul>
      </li>
      <li class="navigation__item navigation__item--borderless"><a href="/">Left item 2</a></li>
    </ul>
    <ul class="navigation__list navigation__list--right" data-accordion-menu data-slide-speed="0" data-multi-open="false">
      <li class="navigation__item navigation__item--borderless">
        <a href="#">Second right item 1</a>
        <ul class="navigation__list">
          <li><a href="#">Second right item 1aaaaaaaaaaaaaaaaaaaaaaa</a></li>
          <li><a href="#">Second right item 1b</a></li>
          <li><a href="#">Second right item 1c</a></li>
        </ul>
      </li>
      <li class="navigation__item navigation__item--borderless"><a href="#">Second right item 2</a></li>
      <li class="navigation__item navigation__item--borderless">
        <a href="#">Second right item 3</a>
        <ul class="navigation__list">
          <li><a href="#">Second right item 3</a></li>
          <li><a href="#">Second right item 3b</a></li>
          <li><a href="#">Second right item 3ccccccccccccccccccccccc</a></li>
        </ul>
      </li>
    </ul>
  </nav>
  <button class="navigation__button navigation__button--close" aria-label="Close menu" type="button" data-toggle="main-menu">
    <span aria-hidden="true">&times;</span>
  </button>
</section>

app/views/application/header/_search.html.erb
<form class="search-bar" action="/" method="get">
  <label class="show-for-sr" for="keyword">Search</label>
  <input class="search-bar__input" id="keyword" type="text" name="keyword" placeholder="Search">
  <button class="search-bar__button" type="submit" placeholder="Submit" aria-label="Search Button" ></button>
</form>

app/views/fruits/_form.html.erb
<%= form_with(model: fruit, local: true) do |form| %>
  <% if fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
        <% fruit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :taste %>
    <%= form.text_area :taste %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fruits/edit.html.erb
<h1>Editing Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Show', @fruit %> |
<%= link_to 'Back', fruits_path %>

app/views/fruits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fruits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Colour</th>
      <th>Taste</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fruits.each do |fruit| %>
      <tr>
        <td><%= fruit.name %></td>
        <td><%= fruit.colour %></td>
        <td><%= fruit.taste %></td>
        <td><%= link_to 'Show', fruit %></td>
        <td><%= link_to 'Edit', edit_fruit_path(fruit) %></td>
        <td><%= link_to 'Destroy', fruit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fruit', new_fruit_path %>

app/views/fruits/new.html.erb
<h1>New Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Back', fruits_path %>

app/views/fruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fruit.name %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @fruit.colour %>
</p>

<p>
  <strong>Taste:</strong>
  <%= @fruit.taste %>
</p>

<%= link_to 'Edit', edit_fruit_path(@fruit) %> |
<%= link_to 'Back', fruits_path %>

app/views/home/_form.html.erb
<form>
  <fieldset>
    <label id="textInputLabel" for="textInput">Text input</label>
    <input type="text" name="textInput" id="textInput" aria-labelledby="textInputLabel" aria-describedby="textInputDescription">
    <small id="textInputDescription" class="form__help-text">A small amount of text can be entered here.</small>

    <label id="numericInputLabel" for="numericInput">Numeric input</label>
    <input type="number" name="numericInput" id="numericInput" aria-labelledby="numericInputLabel" aria-describedby="numericInputDescription" required>
    <small id="numericInputDescription" class="form__help-text">Any number between 0 and 100 can be entered.</small>

    <label id="textAreaLabel" for="textArea">Text area</label>
    <textarea name="textArea" id="textArea" aria-labelledby="textAreaLabel" aria-describedby="textAreaDescription"></textarea>
    <small id="textAreaDescription" class="form__help-text">A large amount of text can be entered here.</small>
  </fieldset>
  <label id="selectInputLabel" for="selectInput">Select input
    <select id="selectInput" aria-labelledby="selectInputLabel">
      <option value="starbuck">Starbuck</option>
      <option value="husker">Husker</option>
      <option value="hotdog">Hot Dog</option>
      <option value="apollo">Apollo</option>
    </select>
  </label>
  <fieldset>
    <legend>Radio input</legend>
    <input type="radio" name="battleStarGalactica" value="Starbuck" id="battleStarGalacticaStarbuck" aria-labelledby="battleStarGalacticaStarbuckLabel">
    <label id="battleStarGalacticaStarbuckLabel" for="battleStarGalacticaStarbuck">Starbuck</label>
    <input type="radio" name="battleStarGalactica" value="Husker" id="battleStarGalacticaHusker" aria-labelledby="battleStarGalacticaHuskerLabel">
    <label id="battleStarGalacticaHuskerLabel" for="battleStarGalacticaHusker">Husker</label>
    <input type="radio" name="battleStarGalactica" value="Hot Dog" id="battleStarGalacticaHotDog" aria-labelledby="battleStarGalacticaHotDogLabel">
    <label id="battleStarGalacticaHotDogLabel" for="battleStarGalacticaHotDog">HotDog</label>
    <input type="radio" name="battleStarGalactica" value="Apollo" id="battleStarGalacticaApollo" aria-labelledby="battleStarGalacticaApolloLabel">
    <label id="battleStarGalacticaApolloLabel" for="battleStarGalacticaApollo">Apollo</label>
  </fieldset>
  <fieldset>
    <legend>Checkbox input</legend>
    <input id="checkbox1" type="checkbox" name="checkboxes" value="checkbox1" aria-labelledby="checkbox1Label"><label id="checkbox1Label" for="checkbox1">Checkbox 1</label>
    <input id="checkbox2" type="checkbox" name="checkboxes" value="checkbox2" aria-labelledby="checkbox2Label"><label id="checkbox2Label" for="checkbox2">Checkbox 2</label>
    <input id="checkbox3" type="checkbox" name="checkboxes" value="checkbox3" aria-labelledby="checkbox3Label"><label id="checkbox3Label" for="checkbox3">Checkbox 3</label>
  </fieldset>
  <div class="button-group button-group--spaced button-group--reversed">
    <input type="submit" class="button" value="Submit"/>
    <a class="button secondary" href="/">Cancel</a>
  </div>
</form>

app/views/home/index.html.erb
<% provide(:title, "Home") %>

<main>
  <div class="row row--spaced">
    <div class="block">
      <%= render "application/breadcrumb" %>
    </div>
  </div>
  <div class="row row--spaced">
    <div class="block block--6">
      <h1>h1. This is a very large header.</h1>
      <h2>h2. This is a large header.</h2>
      <h3>h3. This is a medium header.</h3>
      <h4>h4. This is a moderate header.</h4>
      <h5>h5. This is a small header.</h5>
      <h6>h6. This is a tiny header.</h6>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <p>Links are very standard, and the color is preset to the primary colour. <a href="#">They look like this...</a></p>

      <fieldset>
        <label>Buttons look like this:</label>
        <div class="button-group">
          <a class="button">Primary</a>
          <a class="secondary button">Secondary</a>
          <a class="success button">Success</a>
          <a class="warning button">Warning</a>
          <a class="alert button">Alert</a>
        </div>
      </fieldset>
      <%= render "application/pagination" %>
    </div>
    <div class="block block--6">
      <%= render "form" %>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      <%= strip_tags(yield(:title)) + " – " if content_for?(:title) %>
      Lighthouse Ci Test
    </title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Lighthouse Ci Test <%= Rails.application.config.version %> (<%= l(Rails.application.config.version_time) %>) -->

    <%# CSS should go closest to the top of the document as possible. %>
    <%= stylesheet_pack_tag("application", media: "all", "data-turbolinks-track": "reload") %>

    <%# JavaScript must be in head for Turbolinks to work. %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload", defer: true %>

    <%= yield(:head) %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%# Prevents the full URL, including potentially sensitive query strings being sent to external origins %>
    <meta name="referrer" content="origin-when-crossorigin">

    <%# Specifies the default name of home screen bookmark in iOS %>
    <meta name="apple-mobile-web-app-title" content="Lighthouse Ci Test">
  </head>
  <body class="no-js">

    <%
      # An example of how to load an image via Webpacker. This image is in
      # app/frontend/images/example.png
    %>
    <%# image_pack_tag "example.png", alt: "Example Image" %>


    <%= render("application/header/header") %>

    <div role="main">
      <%= yield %>    <%= render("application/footer") %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>